### ISSUE TITLE
hi兄弟，imaotai是失效了吗？有没有私信可以聊下？

### ISSUE THREAD

**Issue by JohnyWu** [yazhuo-wyze/smms-java-sdk#1]
hi兄弟，imaotai是失效了吗？有没有私信可以聊下？

**Comment by yazhuo-wyze** [comment]
因为一个小原因，我搬迁和关闭了仓库。并且没有继续维护开发了。最近没有关注，应该是不能用了。

**Comment by JohnyWu** [comment]
我也很久没注意了，今天看了一下，短信验证码收不到了。。。这套程序能继续维护吗？

**Comment by ghost** [comment]
https://github.com/dongyazhuo/imaotai  @JohnyWu
